// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Podcaststudio_winform_CRUD;
//
//    var users = Users.FromJson(jsonString);

namespace Podcaststudio_winform_CRUD
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Users
    {
        [JsonProperty("felhasznaloid")]
        public long Felhasznaloid { get; set; }

        [JsonProperty("nev")]
        public string Nev { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("jelszo")]
        public string Jelszo { get; set; }

        [JsonProperty("telefonszam")]
        public string Telefonszam { get; set; }

        [JsonProperty("szemelyi_szam")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long SzemelyiSzam { get; set; }

        [JsonProperty("szuletesi_datum")]
        public DateTimeOffset SzuletesiDatum { get; set; }

        [JsonProperty("ceg")]
        public long Ceg { get; set; }

        [JsonProperty("cegnev")]
        public string Cegnev { get; set; }

        [JsonProperty("ceg_tipus")]
        public string CegTipus { get; set; }

        [JsonProperty("ado_szam")]
        public string AdoSzam { get; set; }

        [JsonProperty("bankszamlaszam")]
        public string Bankszamlaszam { get; set; }

        [JsonProperty("orszag")]
        public string Orszag { get; set; }

        [JsonProperty("iranyitoszam")]
        public string Iranyitoszam { get; set; }

        [JsonProperty("varos")]
        public string Varos { get; set; }

        [JsonProperty("utca")]
        public string Utca { get; set; }

        [JsonProperty("utca_jellege")]
        public string UtcaJellege { get; set; }

        [JsonProperty("hazszam")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Hazszam { get; set; }

        [JsonProperty("epulet")]
        public string Epulet { get; set; }

        [JsonProperty("lepcsohaz")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Lepcsohaz { get; set; }

        [JsonProperty("emelet")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Emelet { get; set; }

        [JsonProperty("ajto")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Ajto { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }
    }

    public partial class Users
    {
        public static Users FromJson(string json) => JsonConvert.DeserializeObject<Users>(json, Podcaststudio_winform_CRUD.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Users self) => JsonConvert.SerializeObject(self, Podcaststudio_winform_CRUD.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
